import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { execFile, execFileSync } from "node:child_process";
import { createServer } from "node:http";
import { promisify } from "node:util";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const PACKAGE_JSON = JSON.parse(fs.readFileSync(path.join(ROOT, "package.json"), "utf8"));
const PACKAGE_VERSION = PACKAGE_JSON.version;
const escapeRegExp = (value) => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
// The stub OOPS! server below runs in this process, so builds that call it must not
// block the event loop the way execFileSync does.
const execFileAsync = promisify(execFile);

test("build-site produces the expected publish artifacts for the bundled example", () => {
  assert.match(PACKAGE_VERSION, /^\d+\.\d+\.\d+$/);
  assert.equal(PACKAGE_JSON.engines.node, ">=22.19.0");
  assert.doesNotMatch(PACKAGE_JSON.engines.node, /</g, "the Node engine should not impose an upper version limit");
  assert.equal(PACKAGE_JSON.repository.url, "git+https://github.com/ecrum19/ocg.git");
  assert.equal(PACKAGE_JSON.publishConfig.registry, "https://registry.npmjs.org/");
  for (const dependency of ["rdf-parse", "graphology", "graphology-layout-forceatlas2", "graphology-layout-noverlap", "sigma"]) {
    assert.ok(PACKAGE_JSON.dependencies?.[dependency], `${dependency} should be a declared dependency`);
  }

  execFileSync("node", ["scripts/build-site.mjs"], {
    cwd: ROOT,
    stdio: "pipe"
  });

  const requiredFiles = [
    "site/index.html",
    "site/favicon.ico",
    "site/favicon.png",
    "site/ocg-favicon.png",
    "site/ontology-reference.html",
    "site/ontology-graph.html",
    "site/spec/index.html",
    "site/usage-guide.html",
    "site/assets/vendor/graphology.umd.min.js",
    "site/assets/vendor/sigma.min.js",
    "site/assets/ontology_graph_data.json",
    "site/assets/ontology_hierarchy.ttl",
    "site/terms/Capability.html",
    "site/terms/index.html"
  ];

  for (const relative of requiredFiles) {
    assert.equal(fs.existsSync(path.join(ROOT, relative)), true, `${relative} should exist`);
  }
  assert.equal(fs.existsSync(path.join(ROOT, "site/iri-resolver.html")), false, "the optional persistent IRI resolver should stay disabled by default");
  assert.equal(fs.existsSync(path.join(ROOT, "site/ontology-pitfalls.html")), false, "the optional OOPS! pitfall report should stay disabled by default");
  assert.equal(fs.existsSync(path.join(ROOT, "site/assets/ontology_pitfalls.json")), false);
  assert.equal(fs.existsSync(path.join(ROOT, "site/persistent-iri")), false, "the optional w3id deployment bundle should stay disabled by default");

  const indexHtml = fs.readFileSync(path.join(ROOT, "site/index.html"), "utf8");
  const stylesCss = fs.readFileSync(path.join(ROOT, "site/assets/css/ocg.css"), "utf8");
  assert.match(indexHtml, /<link rel="stylesheet" href="assets\/css\/ocg\.css\?v=[0-9a-f]{10}" \/>/);
  assert.doesNotMatch(indexHtml, /<style>/, "shared styles should be linked instead of inlined into every page");
  assert.match(
    indexHtml,
    /fonts\.googleapis\.com\/css2\?family=IBM\+Plex\+Sans:wght@400;500;600&amp;family=IBM\+Plex\+Mono:wght@400;500&amp;display=swap/,
    "each font family should be requested once with the weights its roles use"
  );
  assert.match(stylesCss, /^\/\* Generated by OCG v/);
  assert.match(stylesCss, /@layer ocg\.tokens, ocg\.base, ocg\.layout, ocg\.components, ocg\.pages, ocg\.theme;/);
  assert.match(stylesCss, /--ocg-color-page: #f7f7f8;/);
  assert.match(stylesCss, /--ocg-font-heading: "IBM Plex Sans", sans-serif;/);
  assert.match(stylesCss, /--ocg-radius-md: 6px;/);
  assert.match(stylesCss, /--ocg-button-radius: var\(--ocg-radius-md\);/);
  assert.doesNotMatch(stylesCss, /@layer ocg\.theme \{/, "the theme layer is only emitted for configured component overrides");
  assert.doesNotMatch(stylesCss, /gradient\(/, "the default theme uses flat fills");
  const declaredTokens = new Set([...stylesCss.matchAll(/(--ocg-[\w-]+)\s*:/g)].map((match) => match[1]));
  const undeclaredTokens = [...new Set([...stylesCss.matchAll(/var\((--ocg-[\w-]+)/g)].map((match) => match[1]))]
    .filter((token) => !declaredTokens.has(token));
  assert.deepEqual(undeclaredTokens, [], "every referenced --ocg-* token should be declared");
  assert.match(indexHtml, /Example Capability Vocabulary/);
  assert.match(indexHtml, /rel="icon" href="favicon\.ico"/);
  assert.match(indexHtml, /rel="icon" type="image\/png" sizes="512x512" href="favicon\.png"/);
  assert.match(indexHtml, /Config-First Ontology Companion/);
  assert.match(indexHtml, /A config-first companion site for your ontology\./);
  assert.doesNotMatch(indexHtml, /Single-Ontology|one ontology per repository|one vocabulary-oriented GitHub Pages site per fork/);
  assert.match(indexHtml, />OWL Ontology</);
  assert.match(indexHtml, />Specification</);
  assert.doesNotMatch(indexHtml, />Spec Page</);
  assert.match(indexHtml, /href="terms\/index\.html">Terms</);
  assert.match(indexHtml, /href="spec\/index\.html">Specification</);
  assert.match(indexHtml, /hero-action-group--artifacts" style="--artifact-count: 3/);
  assert.match(indexHtml, /class="card-grid featured-terms-grid"/);
  assert.match(indexHtml, /class="card featured-term-card"/);
  assert.match(stylesCss, /\.featured-term-card h3 a[\s\S]*overflow-wrap: anywhere/);
  assert.match(indexHtml, /class="site-footer-generator"/);
  assert.match(indexHtml, /class="site-footer-separator" aria-hidden="true">\|<\/span>/);
  assert.match(indexHtml, new RegExp(`Generated with <strong>OCG<\\/strong> v${escapeRegExp(PACKAGE_VERSION)}`));
  assert.match(indexHtml, /class="ocg-footer-repository"/);
  assert.match(indexHtml, /src="ocg-favicon\.png"/);
  assert.match(indexHtml, /href="https:\/\/github\.com\/ecrum19\/ocg"/);
  assert.match(indexHtml, /href="https:\/\/github\.com\/ecrum19\/ocg#readme"/);
  assert.doesNotMatch(indexHtml, /Ontology Companion Generator template example\./);
  assert.doesNotMatch(indexHtml, /Edit ocg\.config\.json and the source\//);
  assert.match(indexHtml, /href="usage-guide\.html#home">How To</);
  assert.match(indexHtml, /<dt>Preferred Prefix<\/dt>\s*<dd><code>ecv<\/code><\/dd>/, "vann:preferredNamespacePrefix should render under the canonical URI");
  assert.doesNotMatch(indexHtml, /href="ontology-pitfalls\.html"/);
  assert.match(indexHtml, /href="usage-guide\.html#artifacts">How To</);
  assert.match(indexHtml, />View File</);
  for (const label of ["Specification Source", "Basic Capability Example", "Advanced Capability Example"]) {
    assert.match(indexHtml, new RegExp(`data-label="${escapeRegExp(label)}"`));
  }
  for (const label of ["Config Schema", "GitHub Pages Workflow", "Source Replacement Guide"]) {
    assert.doesNotMatch(indexHtml, new RegExp(`data-label="${escapeRegExp(label)}"`));
  }
  assert.doesNotMatch(indexHtml, />Open (TTL|File|Example)</);
  assert.doesNotMatch(indexHtml, /<dt>Namespace<\/dt>/);
  assert.match(indexHtml, /id="copy-namespace"/);
  assert.match(indexHtml, /<h2>Repository Workflow<\/h2>/);
  assert.match(indexHtml, /These cards come directly from ocg\.config\.json/);
  assert.match(indexHtml, /<h2>Artifact Viewer<\/h2>/);
  assert.match(indexHtml, /class="section section--overview"/);
  assert.match(stylesCss, /\.page-home \.section--overview \.section-note \{\s*max-width: none;/);
  assert.match(stylesCss, /\.page-home \.section--overview \.card p,[\s\S]*?overflow-wrap: anywhere;/);
  assert.match(stylesCss, /\.site-header \{[\s\S]*?flex-wrap: wrap;/);
  assert.match(stylesCss, /\.brand \{[\s\S]*?flex: 1 1 360px;/);
  assert.match(stylesCss, /\.brand-copy strong,[\s\S]*?word-break: break-word;/);
  assert.match(indexHtml, /<aside class="page-toc" aria-label="On this page">/);
  assert.match(indexHtml, /href="#ontology-snapshot">Ontology Snapshot/);
  assert.match(indexHtml, /href="#repository-workflow">Repository Workflow/);
  assert.match(indexHtml, /href="#featured-terms">Featured Terms/);
  assert.match(indexHtml, /class="page-content-layout"/);
  assert.match(indexHtml, /data-page-toc-toggle/);
  assert.match(indexHtml, /function setPageTocCollapsed/);
  assert.match(indexHtml, /page-content-layout--toc-collapsed/);
  assert.match(indexHtml, /class="page-toc-toggle-icon"/);
  assert.match(stylesCss, /page-toc\.is-collapsed \.page-toc-toggle-icon \{\s*transform: rotate\(180deg\);/);
  assert.match(stylesCss, /\.page-toc\.is-collapsed \.page-toc-panel \{[\s\S]*?height: 44px;[\s\S]*?max-height: 44px;/);
  assert.match(stylesCss, /\.page-toc\.is-collapsed nav \{[\s\S]*?opacity: 0;/);
  for (const source of [indexHtml, stylesCss]) {
    assert.doesNotMatch(source, /page-toc-expanded-height|page-toc-panel-expanded-height|pageTocPanel\.scrollHeight|max-height: 0/);
  }
  assert.match(stylesCss, /\.page-toc-panel \{[^}]*background: var\(--ocg-panel-background\);/);
  assert.doesNotMatch(stylesCss, /\.page-toc-panel \{[^}]*backdrop-filter: blur/);
  assert.match(stylesCss, /--ocg-toc-motion: 0\.24s;/);
  assert.match(stylesCss, /--ocg-toc-ease: cubic-bezier\(0\.22, 1, 0\.36, 1\);/);
  assert.doesNotMatch(indexHtml, /data-page-toc-icon=/);

  const referenceHtml = fs.readFileSync(path.join(ROOT, "site/ontology-reference.html"), "utf8");
  assert.match(referenceHtml, /id="ontology-hierarchy"/);
  assert.match(referenceHtml, /<h2>Ontology Structure<\/h2>/);
  assert.match(referenceHtml, /class="hierarchy-tree"/);
  assert.match(referenceHtml, /class="hierarchy-links"/);
  assert.match(referenceHtml, /href="terms\/Capability\.html"><span>Capability<\/span>/);
  for (const heading of ["Classes", "Object Properties", "Datatype Properties", "Annotation Properties", "Concepts"]) {
    assert.match(referenceHtml, new RegExp(`<h2>${heading}<\\/h2>`));
  }
  assert.doesNotMatch(referenceHtml, /Classs|Propertys/);
  assert.match(referenceHtml, /href="#reference-overview">Overview/);
  assert.match(referenceHtml, /href="#ontology-hierarchy">Ontology Structure/);
  assert.match(referenceHtml, /href="#reference-class">Classes/);
  assert.match(referenceHtml, /id="reference-objectProperty"/);

  const termHtml = fs.readFileSync(path.join(ROOT, "site/terms/Capability.html"), "utf8");
  assert.match(termHtml, /<link rel="stylesheet" href="\.\.\/assets\/css\/ocg\.css\?v=[0-9a-f]{10}" \/>/);
  assert.match(termHtml, /href="#term-overview">ecv:Capability/);
  assert.match(termHtml, /href="#outgoing-relationships">Outgoing Relationships/);
  assert.match(termHtml, /href="#incoming-relationships">Incoming Relationships/);
  const termsIndexHtml = fs.readFileSync(path.join(ROOT, "site/terms/index.html"), "utf8");
  assert.match(termsIndexHtml, /<aside class="page-toc" aria-label="On this page">/);
  assert.match(termsIndexHtml, /href="#terms-index">Overview/);
  assert.match(termsIndexHtml, /href="#terms-class">Classes/);
  assert.match(termsIndexHtml, /id="terms-objectProperty"/);
  assert.match(stylesCss, /\.page-toc\.is-collapsed \{\s*width: 44px;/);
  assert.match(stylesCss, /\.page-toc\.is-collapsed \.page-toc-panel \{[\s\S]*?height: 44px;/);

  const navHtml = indexHtml.match(/<nav class="site-nav">([\s\S]*?)<\/nav>/)?.[1] || "";
  const navOrder = [
    'href="index.html">Home',
    'href="ontology-reference.html">Reference',
    'href="terms/index.html">Terms',
    'href="ontology-graph.html">Graph',
    'href="spec/index.html">Specification'
  ];
  let previousNavIndex = -1;
  for (const item of navOrder) {
    const itemIndex = navHtml.indexOf(item);
    assert.ok(itemIndex > previousNavIndex, `${item} should follow the configured navigation order`);
    previousNavIndex = itemIndex;
  }

  const graphData = JSON.parse(
    fs.readFileSync(path.join(ROOT, "site/assets/ontology_graph_data.json"), "utf8")
  );
  assert.equal(graphData.project.shortName, "ECV");
  assert.ok(graphData.nodes.some((node) => node.qname === "ecv:Capability"));
  assert.ok(graphData.nodes.every((node) => Number.isFinite(node.degree)));
  assert.ok(graphData.edges.every((edge) => edge.id && edge.predicateQname));
  assert.equal(graphData.modes["predicate-nodes"].nodes.length, graphData.nodes.length);
  assert.equal(graphData.modes["predicate-nodes"].edges.length, graphData.edges.length);
  assert.ok(
    graphData.modes["predicate-edges"].nodes.every(
      (node) => !["objectProperty", "datatypeProperty", "annotationProperty"].includes(node.termType)
    )
  );
  assert.ok(graphData.modes["predicate-edges"].edges.some((edge) => edge.predicateQname === "ecv:hasRequirement"));
  const graphLabelWidth = (node) => {
    let width = 18;
    for (const character of String(node.qname || node.label || "")) {
      width += /[MW@#%&]/.test(character)
        ? 8.6
        : /[ilI1|.:,'`]/.test(character)
          ? 4.2
          : /[A-Z0-9]/.test(character)
            ? 7.4
            : 6.6;
    }
    return Math.min(420, Math.max(72, width));
  };
  for (const node of graphData.nodes) {
    assert.ok(Number.isFinite(node.x) && Number.isFinite(node.y), `${node.qname} should have an initial position`);
  }
  for (const [modeName, mode] of Object.entries(graphData.modes)) {
    const isolatedNodes = mode.nodes.filter((node) => node.degree === 0);
    if (isolatedNodes.length > 1) {
      assert.equal(
        new Set(isolatedNodes.map((node) => node.y)).size,
        1,
        `${modeName} should pack isolated terms into a compact horizontal band`
      );
    }
  }
  for (let leftIndex = 0; leftIndex < graphData.nodes.length; leftIndex += 1) {
    const left = graphData.nodes[leftIndex];
    for (let rightIndex = leftIndex + 1; rightIndex < graphData.nodes.length; rightIndex += 1) {
      const right = graphData.nodes[rightIndex];
      const verticalDistance = Math.abs(left.y - right.y);
      const leftLabel = { start: left.x + 10, end: left.x + 10 + graphLabelWidth(left) };
      const rightLabel = { start: right.x + 10, end: right.x + 10 + graphLabelWidth(right) };
      const labelsOverlapHorizontally = leftLabel.start < rightLabel.end && rightLabel.start < leftLabel.end;
      assert.ok(
        !(labelsOverlapHorizontally && verticalDistance < 32),
        `${left.qname} and ${right.qname} should not overlap in the initial label layout`
      );
    }
  }
  const firstLayout = Object.fromEntries(
    Object.entries(graphData.modes).map(([modeName, mode]) => [
      modeName,
      mode.nodes.map(({ id, x, y }) => ({ id, x, y }))
    ])
  );
  execFileSync("node", ["scripts/build-site.mjs"], { cwd: ROOT, stdio: "pipe" });
  const rebuiltGraphData = JSON.parse(
    fs.readFileSync(path.join(ROOT, "site/assets/ontology_graph_data.json"), "utf8")
  );
  const rebuiltLayout = Object.fromEntries(
    Object.entries(rebuiltGraphData.modes).map(([modeName, mode]) => [
      modeName,
      mode.nodes.map(({ id, x, y }) => ({ id, x, y }))
    ])
  );
  assert.deepEqual(rebuiltLayout, firstLayout, "graph coordinates should be deterministic across builds");

  const graphHtml = fs.readFileSync(path.join(ROOT, "site/ontology-graph.html"), "utf8");
  assert.match(graphHtml, /Ontology Network/);
  assert.match(graphHtml, /WebVOWL/);
  assert.match(graphHtml, /assets\/vendor\/graphology\.umd\.min\.js/);
  assert.match(graphHtml, /assets\/vendor\/sigma\.min\.js/);
  assert.match(graphHtml, /id="webvowl-frame"/);
  assert.match(graphHtml, /service\.tib\.eu\/webvowl/);
  assert.match(graphHtml, /id="sigma-toggle-external"/);
  assert.match(graphHtml, /id="sigma-canvas" class="sigma-canvas"/);
  assert.match(graphHtml, /class="sigma-panel"/);
  assert.match(graphHtml, /data-graph-expand="custom-graph-panel"/);
  assert.match(graphHtml, /data-graph-expand="webvowl-graph-panel"/);
  assert.match(graphHtml, /class="graph-expand-btn graph-expand-btn--icon"/);
  assert.match(graphHtml, /data-graph-expand-icon="compress"/);
  assert.match(graphHtml, /Press Esc to exit full screen\./);
  assert.match(graphHtml, /data-sigma-controls-toggle/);
  assert.match(graphHtml, /id="sigma-selection-block"/);
  assert.doesNotMatch(graphHtml, />Edge Details</);
  assert.doesNotMatch(graphHtml, /id="sigma-edge-hover-info"/);
  assert.match(graphHtml, /function setGraphControlsCollapsed/);
  assert.match(graphHtml, /graph-controls-collapsed/);
  assert.doesNotMatch(graphHtml, /graph-panel-toolbar/);
  assert.doesNotMatch(graphHtml, /data-graph-expand-label/);
  assert.match(stylesCss, /height: 100%;\s+min-height: 0;\s+border: 0;/);
  assert.match(stylesCss, /\.sigma-graph-panel:is\(\.graph-panel--expanded, :fullscreen\) \.sigma-panel \{/);
  assert.doesNotMatch(stylesCss, /-webkit-full-screen/, "the graph script only uses the standard Fullscreen API");
  assert.match(graphHtml, /function toggleGraphPanel/);
  assert.match(graphHtml, /requestFullscreen/);
  assert.match(graphHtml, /graph-panel--expanded/);
  assert.match(graphHtml, /Predicates as Nodes/);
  assert.match(graphHtml, /Predicates as Edges/);
  assert.match(graphHtml, /function toViewportPoint/);
  assert.match(graphHtml, /function selectEdge/);
  assert.match(graphHtml, /function updateDetailForEdge/);
  assert.match(graphHtml, /function revealSelectionDetails/);
  assert.match(graphHtml, /sidebarEl\.scrollTo/);
  assert.match(graphHtml, /EDGE_HIT_TOLERANCE = 14/);
  assert.match(graphHtml, /function findNearbyEdge/);
  assert.match(graphHtml, /function getNodeAtPoint/);
  assert.match(graphHtml, /function getNodeLabelPlacement/);
  assert.match(graphHtml, /getNodeDisplayData/);
  assert.match(graphHtml, /measureText\(label\)/);
  assert.match(graphHtml, /function updateFallbackHover/);
  assert.match(graphHtml, /function selectNode/);
  assert.match(graphHtml, /hoverRenderer: \(\) => \{\}/);
  assert.match(graphHtml, /enableEdgeHoverEvents: false/);
  assert.match(graphHtml, /enableEdgeClickEvents: false/);
  assert.doesNotMatch(graphHtml, /function claimClick/);
  assert.doesNotMatch(graphHtml, /nativeClickHandled/);
  assert.match(graphHtml, /aria-label="Ontology Network mode"/);
  assert.match(graphHtml, /container\.addEventListener\("pointermove", updateFallbackHover/);
  assert.match(graphHtml, /container\.addEventListener\("pointerleave"/);
  assert.match(graphHtml, /container\.addEventListener\("click", handleGraphClick/);
  assert.match(graphHtml, /interactionAbortController\?\.abort\(\)/);
  assert.match(graphHtml, /baseForceLabel/);
  assert.match(graphHtml, /function drawReadableNodeLabel/);
  assert.doesNotMatch(graphHtml, /function runGraphologyRelaxation/);
  assert.match(graphHtml, /labelGridCellSize: LABEL_SETTINGS\.gridCellSize/);
  assert.match(graphHtml, /labelDensity: LABEL_SETTINGS\.density/);
  assert.match(graphHtml, /stagePadding: 72/);
  assert.match(graphHtml, /forceAllLabels/);
  assert.match(graphHtml, /if \(selectedEdge === edgeId\)/);
  assert.match(graphHtml, /if \(selectedNode === node\)/);
  assert.match(graphHtml, /renderer\.getMouseCaptor\(\)/);
  assert.match(graphHtml, /window\.addEventListener\("blur", endDrag, \{ signal \}\)/);
  assert.match(graphHtml, /renderer\.on\("downNode"/);
  assert.doesNotMatch(graphHtml, /renderer\.on\("clickNode"/);
  assert.doesNotMatch(graphHtml, /renderer\.on\("clickEdge"/);
  assert.doesNotMatch(graphHtml, /renderer\.on\("clickStage"/);
  assert.doesNotMatch(graphHtml, /renderer\.on\("enterNode"/);
  assert.doesNotMatch(graphHtml, /renderer\.on\("enterEdge"/);
  assert.match(graphHtml, /setupRendererInteractions\(\);/);
  assert.match(graphHtml, /id="sigma-toggle-edge-labels" type="checkbox" checked/);
  assert.match(graphHtml, /renderEdgeLabels: true/);
  assert.match(graphHtml, /edgeLabelRenderer: drawReadableEdgeLabel/);
  assert.match(graphHtml, /edgeLabelSize: LABEL_SETTINGS\.edgeLabelSize/);
  assert.match(graphHtml, /const edgeLabel = edge\.predicateQname \|\| edge\.label \|\| edge\.relation;/);
  assert.match(graphHtml, /label: showEdgeLabels \? attrs\.baseLabel : ""/);
  assert.match(graphHtml, /mouseCaptor\.on\("mousedown"/);
  assert.match(graphHtml, /mouseCaptor\.on\("mousemovebody"/);
  assert.match(stylesCss, /\.sigma-panel \{[\s\S]*?grid-auto-rows: max-content;/);
  assert.match(stylesCss, /\.sigma-block \{[\s\S]*?overflow: visible;/);
  assert.match(graphHtml, /class=\\"sigma-detail-heading\\"/);
  assert.match(graphHtml, /class=\\"sigma-detail-metadata\\"/);
  assert.match(stylesCss, /\.graph-expand-btn--icon svg\[hidden\]/);
  assert.match(graphHtml, /href="usage-guide\.html#graph">How To</);
  assert.doesNotMatch(graphHtml, /<aside class="page-toc"/);

  const specHtml = fs.readFileSync(path.join(ROOT, "site/spec/index.html"), "utf8");
  assert.match(specHtml, /Tools\/respec\/respec-w3c/);
  assert.match(specHtml, /var respecConfig/);
  assert.match(specHtml, /features\.specPage/);
  assert.match(specHtml, /class="site-header ocg-spec-header"/);
  assert.match(specHtml, /<nav class="site-nav" aria-label="Companion site navigation">/);
  assert.match(specHtml, /<link rel="stylesheet" href="\.\.\/assets\/css\/ocg-spec\.css\?v=[0-9a-f]{10}" \/>/);
  assert.match(specHtml, /fonts\.googleapis\.com\/css2\?family=IBM\+Plex\+Sans/, "the ReSpec page should load the theme fonts");
  assert.doesNotMatch(specHtml, /assets\/css\/ocg\.css/, "the ReSpec page must not load the element styles of the main stylesheet");
  const specCss = fs.readFileSync(path.join(ROOT, "site/assets/css/ocg-spec.css"), "utf8");
  assert.match(specCss, /body\.ocg-spec-page \.site-nav \.nav-link \{/, "shared chrome rules should be scoped to outrank the ReSpec styles");
  assert.match(specCss, /body\.ocg-spec-page \{\s*--ocg-spec-header-height: 64px;/);
  assert.match(specCss, /--ocg-button-radius: var\(--ocg-radius-md\);/);
  assert.doesNotMatch(specCss, /@layer|gradient\(/);
  assert.doesNotMatch(specCss, /body\.ocg-spec-page :root/);
  assert.match(specHtml, /rel="icon" href="\.\.\/favicon\.ico"/);
  assert.match(specHtml, /rel="icon" type="image\/png" sizes="512x512" href="\.\.\/favicon\.png"/);
  assert.match(specHtml, /href="\.\.\/index\.html"/);
  assert.match(specHtml, /is-active" href="\.\.\/spec\/index\.html"/);
  assert.match(specHtml, /class="ocg-spec-footer"/);
  assert.match(specHtml, /class="site-footer-separator" aria-hidden="true">\|<\/span>/);
  assert.match(specHtml, new RegExp(`Generated with <strong>OCG<\\/strong> v${escapeRegExp(PACKAGE_VERSION)}`));
  assert.match(specHtml, /class="ocg-footer-repository"/);
  assert.match(specHtml, /src="\.\.\/ocg-favicon\.png"/);
  assert.doesNotMatch(specHtml, /Ontology Companion Generator template example\./);
  assert.doesNotMatch(specHtml, /Edit ocg\.config\.json and the source\//);
  assert.match(specHtml, /href="\.\.\/usage-guide\.html#specification">How To</);

  const guideHtml = fs.readFileSync(path.join(ROOT, "site/usage-guide.html"), "utf8");
  assert.match(guideHtml, /id="existing-repository"/);
  assert.match(guideHtml, /<h2>Existing Repository Integration<\/h2>/);
  assert.match(guideHtml, /vocab\/my-vocabulary\.ttl/);
  assert.match(guideHtml, /Do not copy OCG internals/);
  assert.match(guideHtml, /feature branches cannot overwrite the live site/);
  assert.match(guideHtml, /id="getting-started"/);
  assert.match(guideHtml, /id="accepted-input-formats"/);
  assert.match(guideHtml, /<h2>Accepted Input Formats<\/h2>/);
  assert.match(guideHtml, /id="w3id-publication"/);
  assert.match(guideHtml, /<h2>End-to-End w3id Publication<\/h2>/);
  assert.match(guideHtml, /site\/persistent-iri\/w3id\/ocg\/\.htaccess/);
  assert.match(guideHtml, /Settings → Pages/);
  assert.match(guideHtml, /Accept: text\/turtle/);
  assert.match(guideHtml, /id="persistent-iri-workflow"/);
  assert.match(guideHtml, /<h2>Persistent IRI Deployment<\/h2>/);
  assert.match(guideHtml, /id="persistent-iri"/);
  assert.match(guideHtml, /<h2>Persistent IRI and Content Negotiation<\/h2>/);
  assert.match(guideHtml, /https:\/\/github\.com\/lambdamusic\/Ontospy/);
  assert.match(guideHtml, /site\/persistent-iri\/README\.md/);
  assert.match(guideHtml, /class="section guide-section persistent-iri-section"/);
  assert.match(guideHtml, /class="iri-example">https:\/\/w3id\.org\/your-project\/vocab#Capability/);
  assert.match(guideHtml, /w3id persistent-identifier publishing guide/);
  assert.match(guideHtml, /class="guide-callout guide-callout--instruction"/);
  assert.match(guideHtml, /npm run ocg:build/);
  assert.match(guideHtml, /w3id explanation of identifier redirects/);
  assert.match(guideHtml, /<code>\.htaccess<\/code> examples/);
  assert.match(stylesCss, /\.persistent-iri-section \.section-head \.section-note \{\s*max-width: none;/);
  assert.match(stylesCss, /\.persistent-iri-section > \.guide-steps \{[\s\S]*?gap: 16px;[\s\S]*?margin: 24px 0;/);
  assert.match(guideHtml, /OWL\/XML/);
  assert.match(guideHtml, /source\/ontology\/my-vocabulary\.jsonld/);
  assert.match(guideHtml, /<section class="guide-hero section">\s*<details class="guide-toc" open>/);
  assert.doesNotMatch(guideHtml, />On This Page</);
  assert.match(guideHtml, /class="guide-toc-summary"/);
  assert.match(guideHtml, /aria-label="Usage Guide table of contents"/);
  assert.match(guideHtml, /class="guide-toc-list"/);
  assert.match(guideHtml, /class="guide-toc-item guide-toc-item--level-0"/);
  assert.match(guideHtml, /class="guide-toc-item guide-toc-item--level-1"/);
  assert.match(guideHtml, /href="#graph">.*Ontology Graph/);
  assert.match(guideHtml, /href="#branding">.*Theme, Page Navigation, Footer, and Generator Links/);
  assert.match(guideHtml, /id="components"/);
  assert.match(guideHtml, /id="configuration"/);
  for (const componentId of [
    "project",
    "home",
    "artifacts",
    "persistent-iri",
    "reference",
    "graph",
    "terms",
    "specification",
    "usage-guide",
    "branding",
    "styling"
  ]) {
    assert.match(guideHtml, new RegExp(`id="${componentId}"`));
  }
  for (const option of [
    "$schema",
    "project.maintainer",
    "sources.examples[].description",
    "persistentIri.enabled",
    "persistentIri.documentIri",
    "persistentIri.siteUrl",
    "persistentIri.representations[].mediaType",
    "persistentIri.representations[].destinationName",
    "features.hierarchyAsset",
    "features.hierarchyOverview",
    "hierarchy.rootTerms",
    "hierarchy.maxDepth",
    "hierarchy.maxChildrenPerNode",
    "hierarchy.maxNodes",
    "hierarchy.includePropertyRelations",
    "hierarchy.labelMode",
    "site.home.actions",
    "site.home.metadata",
    "site.home.snapshot.title",
    "site.home.overview.title",
    "site.home.featuredTerms.emptyBody",
    "site.home.examples.linkText",
    "site.home.viewer.viewFileText",
    "site.home.artifacts",
    "site.toc.enabled",
    "site.toc.title",
    "site.toc.collapseLabel",
    "site.toc.expandLabel",
    "site.branding.headerImage",
    "site.branding.favicon",
    "site.customSections[].items",
    "graph.custom.modes.predicateEdges",
    "graph.custom.label",
    "graph.webvowl.height",
    "graph.colors.broader",
    "theme.colors.accentStart",
    "theme.colors.accentBorder",
    "theme.colors.accentStrong",
    "theme.colors.warmAccent",
    "theme.radius.md",
    "theme.components.button.primary.background",
    "theme.components.card.shadow",
    "theme.components.table.stripeBackground",
    "theme.customCss",
    "site.generator.documentationUrl",
    "curation.viewerTabs"
  ]) {
    assert.match(guideHtml, new RegExp(`<code>${option.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}</code>`));
  }
  assert.match(guideHtml, /Predicates as Edges/);
  assert.match(guideHtml, /Complete Configuration Example/);
  assert.match(guideHtml, /Basic Example/);
  assert.match(guideHtml, /id="package-cli"/);
  assert.match(guideHtml, /npm install --save-dev ontology-companion-generator/);
  assert.match(guideHtml, /npm run ocg:build/);

  const workflow = fs.readFileSync(path.join(ROOT, ".github/workflows/publish-pages.yml"), "utf8");
  assert.match(workflow, /branches:\s*\n\s+- main/);
  assert.match(workflow, /node-version: 24/);
  assert.match(workflow, /actions\/checkout@v5/);
  assert.match(workflow, /actions\/setup-node@v6/);
  assert.match(workflow, /actions\/upload-pages-artifact@v5/);
  assert.match(workflow, /actions\/deploy-pages@v5/);
  assert.doesNotMatch(workflow, /actions\/(?:checkout|setup-node|upload-pages-artifact|deploy-pages)@v[234]\b/);
  assert.doesNotMatch(workflow, /test -f site\/ontology-reference\.html/);
  assert.doesNotMatch(workflow, /test -f site\/ontology-graph\.html/);

  const npmWorkflow = fs.readFileSync(path.join(ROOT, ".github/workflows/publish-npm.yml"), "utf8");
  assert.match(npmWorkflow, /tags:\s*\n\s+- "v\*\.\*\.\*"/);
  assert.match(npmWorkflow, /id-token:\s*write/);
  assert.match(npmWorkflow, /registry-url: https:\/\/registry\.npmjs\.org/);
  assert.match(npmWorkflow, /npm install --global npm@latest/);
  assert.match(npmWorkflow, /npm test/);
  assert.match(npmWorkflow, /npm publish/);
  assert.match(npmWorkflow, /actions\/checkout@v5/);
  assert.match(npmWorkflow, /actions\/setup-node@v6/);
  assert.doesNotMatch(npmWorkflow, /actions\/(?:checkout|setup-node)@v[234]\b/);
  assert.match(npmWorkflow, /test "v\$\{PACKAGE_VERSION\}" = "\$\{TAG_NAME\}"/);
  assert.doesNotMatch(npmWorkflow, /NPM_TOKEN/);
});

test("custom theme colors reach shared pages, ReSpec, and Sigma runtime settings", () => {
  const configPath = path.join(ROOT, "ocg.config.json");
  const originalConfigText = fs.readFileSync(configPath, "utf8");
  const originalConfig = JSON.parse(originalConfigText);
  const customColors = {
    pageBackground: "#102027",
    pageBackgroundAlt: "#1b3440",
    panelBackground: "#eef7f8",
    cardBackground: "#ffffff",
    text: "#102027",
    mutedText: "#45606b",
    accent: "#c25d3d",
    accentStart: "#e08a54",
    accentBorder: "#a94832",
    accentStrong: "#7d3328",
    border: "#caa9a0",
    warmAccent: "#e6b85c"
  };

  try {
    fs.writeFileSync(
      configPath,
      JSON.stringify(
        { ...originalConfig, theme: { ...originalConfig.theme, colors: customColors } },
        null,
        2
      )
    );
    execFileSync("node", ["scripts/build-site.mjs"], { cwd: ROOT, stdio: "pipe" });

    const stylesCss = fs.readFileSync(path.join(ROOT, "site/assets/css/ocg.css"), "utf8");
    const specCss = fs.readFileSync(path.join(ROOT, "site/assets/css/ocg-spec.css"), "utf8");
    const graphHtml = fs.readFileSync(path.join(ROOT, "site/ontology-graph.html"), "utf8");
    for (const css of [stylesCss, specCss]) {
      assert.match(css, /--ocg-color-page: #102027;/);
      assert.match(css, /--ocg-color-accent: #c25d3d;/);
      assert.match(css, /--ocg-color-accent-start: #e08a54;/);
      assert.match(css, /--ocg-color-accent-border: #a94832;/);
      assert.match(css, /--ocg-color-warm-accent: #e6b85c;/);
    }
    assert.match(graphHtml, /const THEME_COLOR = \{"text":"#102027","muted":"#45606b","accentStrong":"#7d3328","panel":"#eef7f8","border":"#caa9a0"\}/);
    assert.match(graphHtml, /function colorToRgba\(color, alpha\)/);
  } finally {
    fs.writeFileSync(configPath, originalConfigText);
    execFileSync("node", ["scripts/build-site.mjs"], { cwd: ROOT, stdio: "pipe" });
  }
});

function initThemeTestProject(prefix) {
  const tempDir = fs.mkdtempSync(path.join(ROOT, prefix));
  const cliPath = path.join(ROOT, "bin", "ocg.mjs");
  fs.copyFileSync(path.join(ROOT, "source", "ontology", "example-capability.ttl"), path.join(tempDir, "ontology.ttl"));
  execFileSync(process.execPath, [cliPath, "init", "--ontology", "ontology.ttl"], { cwd: tempDir, stdio: "pipe" });
  const configPath = path.join(tempDir, "ocg.config.json");
  const config = JSON.parse(fs.readFileSync(configPath, "utf8"));
  const run = (command) => execFileSync(process.execPath, [cliPath, command], { cwd: tempDir, stdio: "pipe" });
  return { tempDir, configPath, config, run };
}

function componentOptionPaths() {
  const schema = JSON.parse(fs.readFileSync(path.join(ROOT, "ocg.config.schema.json"), "utf8"));
  const options = [];
  const collect = (properties, optionPath) => {
    for (const [key, definition] of Object.entries(properties)) {
      if (definition.type === "object") {
        collect(definition.properties, [...optionPath, key]);
      } else {
        options.push({ optionPath: [...optionPath, key], ref: definition.$ref });
      }
    }
  };
  for (const [component, definition] of Object.entries(schema.properties.theme.properties.components.properties)) {
    collect(definition.properties, [component]);
  }
  return options;
}

const componentTokenName = (optionPath) =>
  `--ocg-${optionPath.map((part) => part.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`)).join("-")}`;

test("theme radius, component options, fonts, and custom CSS reach the generated stylesheets", () => {
  const { tempDir, configPath, config, run } = initThemeTestProject(".ocg-theme-test-");
  try {
    fs.writeFileSync(path.join(tempDir, "site.css"), ".hero-copy h1 { letter-spacing: 0; }\n");
    fs.writeFileSync(path.join(tempDir, "spec.html"), "<!doctype html><html><head><title>Spec</title></head><body><h1>Spec</h1></body></html>");
    config.sources.spec = "spec.html";
    config.features.specPage = true;
    config.theme = {
      ...config.theme,
      fonts: { heading: "Source Serif 4", body: "system-ui", mono: "ui-monospace" },
      radius: { ...config.theme.radius, md: 3 },
      components: {
        button: { radius: 0, fontWeight: 600, primary: { background: "#123456" } },
        card: { shadow: "lg" },
        table: { stripeBackground: "transparent" }
      },
      customCss: "site.css"
    };
    fs.writeFileSync(configPath, JSON.stringify(config, null, 2));
    run("build");

    const site = path.join(tempDir, "site");
    const stylesCss = fs.readFileSync(path.join(site, "assets", "css", "ocg.css"), "utf8");
    const specCss = fs.readFileSync(path.join(site, "assets", "css", "ocg-spec.css"), "utf8");
    const indexHtml = fs.readFileSync(path.join(site, "index.html"), "utf8");
    const specHtml = fs.readFileSync(path.join(site, "spec", "index.html"), "utf8");

    assert.match(stylesCss, /--ocg-radius-md: 3px;/, "numeric radii are read as pixels");
    const themeLayer = stylesCss.match(/@layer ocg\.theme \{([\s\S]*)\}\s*$/)?.[1] || "";
    for (const declaration of [
      "--ocg-button-radius: 0;",
      "--ocg-button-font-weight: 600;",
      "--ocg-button-primary-background: #123456;",
      "--ocg-card-shadow: var(--ocg-shadow-lg);",
      "--ocg-table-stripe-background: transparent;"
    ]) {
      assert.ok(themeLayer.includes(declaration), `${declaration} should be in the theme layer`);
      assert.ok(specCss.includes(declaration), `${declaration} should reach the ReSpec stylesheet`);
    }
    assert.match(stylesCss, /--ocg-font-heading: "Source Serif 4", sans-serif;/);
    assert.match(stylesCss, /--ocg-font-body: system-ui, sans-serif;/);
    assert.match(stylesCss, /--ocg-font-mono: ui-monospace, monospace;/);
    assert.match(
      indexHtml,
      /fonts\.googleapis\.com\/css2\?family=Source\+Serif\+4:wght@500;600&amp;display=swap/,
      "generic families should not be requested from Google Fonts"
    );

    assert.equal(fs.readFileSync(path.join(site, "assets", "css", "custom.css"), "utf8"), ".hero-copy h1 { letter-spacing: 0; }\n");
    for (const [html, prefix, sheet] of [[indexHtml, "", "ocg"], [specHtml, "../", "ocg-spec"]]) {
      const links = [...html.matchAll(/<link rel="stylesheet" href="([^"]+)"/g)].map((match) => match[1].replace(/\?v=[0-9a-f]{10}$/, ""));
      assert.deepEqual(links, [`${prefix}assets/css/${sheet}.css`, `${prefix}assets/css/custom.css`], "custom CSS should load after the generated stylesheet");
    }
  } finally {
    fs.rmSync(tempDir, { recursive: true, force: true });
  }
});

test("theme validation rejects unknown components, unknown options, and unsafe values", () => {
  const { tempDir, configPath, config, run } = initThemeTestProject(".ocg-theme-validation-test-");
  try {
    const expectInvalid = (theme, message) => {
      fs.writeFileSync(configPath, JSON.stringify({ ...config, theme: { ...config.theme, ...theme } }, null, 2));
      assert.throws(
        () => run("check"),
        (error) => `${error.stdout || ""}${error.stderr || ""}`.includes(message),
        `expected the check to fail with: ${message}`
      );
    };
    expectInvalid({ components: { buton: { radius: "4px" } } }, "theme.components.buton is not a supported component");
    expectInvalid({ components: { button: { color: "#fff" } } }, "theme.components.button.color is not supported");
    expectInvalid({ components: { button: { primary: "#fff" } } }, "theme.components.button.primary must be an object");
    expectInvalid({ components: { card: { background: "red; } body { display: none" } } }, "theme.components.card.background must be a single CSS value");
    expectInvalid({ colors: { ...config.theme.colors, accent: "#fff}" } }, "theme.colors.accent must be a single CSS value");
    expectInvalid({ radius: { ...config.theme.radius, md: -2 } }, "theme.radius.md must be a non-negative number");
    expectInvalid({ radius: { ...config.theme.radius, xxl: "12px" } }, "theme.radius.xxl is not supported");
    expectInvalid({ fonts: { ...config.theme.fonts, body: "Inter, sans-serif" } }, "theme.fonts.body must be a single font family name");
    expectInvalid({ customCss: "site.scss" }, "theme.customCss must be a repository-relative path to a .css file");
    expectInvalid({ customCss: "missing.css" }, "Configured file does not exist: missing.css");
  } finally {
    fs.rmSync(tempDir, { recursive: true, force: true });
  }
});

test("every documented component option maps to a declared style token", () => {
  const tokensCss = fs.readFileSync(path.join(ROOT, "templates", "styles", "tokens.css"), "utf8");
  const options = componentOptionPaths();
  assert.ok(options.length > 40, "the schema should document the component options");
  for (const { optionPath } of options) {
    assert.match(
      tokensCss,
      new RegExp(`${escapeRegExp(componentTokenName(optionPath))}: `),
      `${optionPath.join(".")} should have a default in templates/styles/tokens.css`
    );
  }

  // Setting every documented option checks the generator's registry against the schema.
  const { tempDir, configPath, config, run } = initThemeTestProject(".ocg-theme-options-test-");
  try {
    const components = {};
    const expected = options.map(({ optionPath, ref }, index) => {
      const value = {
        "#/$defs/cssColor": `rgb(1 2 ${index})`,
        "#/$defs/cssLength": `${index + 1}px`,
        "#/$defs/cssShadow": "md",
        "#/$defs/cssFontWeight": 500
      }[ref];
      assert.ok(value !== undefined, `${optionPath.join(".")} uses an unexpected definition ${ref}`);
      let target = components;
      for (const key of optionPath.slice(0, -1)) {
        target = target[key] ||= {};
      }
      target[optionPath.at(-1)] = value;
      return `${componentTokenName(optionPath)}: ${ref === "#/$defs/cssShadow" ? "var(--ocg-shadow-md)" : value};`;
    });
    fs.writeFileSync(configPath, JSON.stringify({ ...config, theme: { ...config.theme, components } }, null, 2));
    run("build");
    const stylesCss = fs.readFileSync(path.join(tempDir, "site", "assets", "css", "ocg.css"), "utf8");
    const themeLayer = stylesCss.match(/@layer ocg\.theme \{([\s\S]*)\}\s*$/)?.[1] || "";
    for (const declaration of expected) {
      assert.ok(themeLayer.includes(declaration), `${declaration} should be emitted`);
    }
  } finally {
    fs.rmSync(tempDir, { recursive: true, force: true });
  }
});

test("build-site accepts the documented primary ontology formats", () => {
  const configPath = path.join(ROOT, "ocg.config.json");
  const originalConfigText = fs.readFileSync(configPath, "utf8");
  const originalConfig = JSON.parse(originalConfigText);
  const tempDir = fs.mkdtempSync(path.join(ROOT, ".ocg-format-test-"));
  const formatInputs = [
    {
      format: "turtle",
      extension: "ttl",
      content: `@prefix ecv: <https://example.org/ecv#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
ecv:FormatClass a owl:Class ; rdfs:label "Format Class" .`
    },
    {
      format: "rdfxml",
      extension: "rdf",
      content: `<?xml version="1.0"?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:owl="http://www.w3.org/2002/07/owl#" xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">
  <owl:Class rdf:about="https://example.org/ecv#FormatClass"><rdfs:label>Format Class</rdfs:label></owl:Class>
</rdf:RDF>`
    },
    {
      format: "jsonld",
      extension: "jsonld",
      content: JSON.stringify({
        "@context": {
          ecv: "https://example.org/ecv#",
          owl: "http://www.w3.org/2002/07/owl#",
          rdfs: "http://www.w3.org/2000/01/rdf-schema#"
        },
        "@id": "ecv:FormatClass",
        "@type": "owl:Class",
        "rdfs:label": "Format Class"
      })
    },
    {
      format: "ntriples",
      extension: "nt",
      content: `<https://example.org/ecv#FormatClass> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#Class> .\n<https://example.org/ecv#FormatClass> <http://www.w3.org/2000/01/rdf-schema#label> "Format Class" .`
    }
  ];

  try {
    for (const input of formatInputs) {
      const sourcePath = path.join(tempDir, `ontology.${input.extension}`);
      fs.writeFileSync(sourcePath, input.content);
      const testConfig = {
        ...originalConfig,
        sources: {
          ...originalConfig.sources,
          ontology: sourcePath,
          ontologyFormat: input.format
        }
      };
      fs.writeFileSync(configPath, JSON.stringify(testConfig, null, 2));
      execFileSync("node", ["scripts/build-site.mjs"], { cwd: ROOT, stdio: "pipe" });

      const graphData = JSON.parse(
        fs.readFileSync(path.join(ROOT, "site/assets/ontology_graph_data.json"), "utf8")
      );
      assert.equal(graphData.sourceFormat, input.format);
      assert.ok(graphData.nodes.some((node) => node.uri === "https://example.org/ecv#FormatClass"));
    }

    const unsupportedPath = path.join(tempDir, "ontology.trig");
    fs.writeFileSync(unsupportedPath, "<https://example.org/ecv#FormatClass> {} .");
    fs.writeFileSync(
      configPath,
      JSON.stringify(
        {
          ...originalConfig,
          sources: { ...originalConfig.sources, ontology: unsupportedPath, ontologyFormat: "auto" }
        },
        null,
        2
      )
    );
    assert.throws(
      () => execFileSync("node", ["scripts/build-site.mjs"], { cwd: ROOT, stdio: "pipe" }),
      (error) => `${error.stdout || ""}${error.stderr || ""}`.includes("Unsupported ontology format")
    );

    fs.writeFileSync(
      configPath,
      JSON.stringify(
        {
          ...originalConfig,
          graph: {
            ...originalConfig.graph,
            webvowl: {
              ...originalConfig.graph.webvowl,
              ontologyUrl: originalConfig.project.namespace
            }
          }
        },
        null,
        2
      )
    );
    assert.throws(
      () => execFileSync("node", ["scripts/build-site.mjs", "--check"], { cwd: ROOT, stdio: "pipe" }),
      (error) => `${error.stdout || ""}${error.stderr || ""}`.includes("must be a public ontology document URL")
    );
  } finally {
    fs.writeFileSync(configPath, originalConfigText);
    fs.rmSync(tempDir, { recursive: true, force: true });
    execFileSync("node", ["scripts/build-site.mjs"], { cwd: ROOT, stdio: "pipe" });
  }
});

test("persistent IRI support emits static RDF targets, a browser resolver, and w3id rules", () => {
  const configPath = path.join(ROOT, "ocg.config.json");
  const originalConfigText = fs.readFileSync(configPath, "utf8");
  const originalConfig = JSON.parse(originalConfigText);
  const tempDir = fs.mkdtempSync(path.join(ROOT, ".ocg-persistent-iri-test-"));
  const ontologyPath = path.join(tempDir, "vocabulary.ttl");
  const jsonldPath = path.join(tempDir, "vocabulary.jsonld");

  try {
    fs.writeFileSync(
      ontologyPath,
      `@prefix ex: <https://w3id.org/example/vocab#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
ex:ExampleTerm a owl:Class ; rdfs:label "Example Term" .\n`
    );
    fs.writeFileSync(
      jsonldPath,
      JSON.stringify({
        "@context": { ex: "https://w3id.org/example/vocab#", owl: "http://www.w3.org/2002/07/owl#" },
        "@id": "ex:ExampleTerm",
        "@type": "owl:Class"
      })
    );
    const testConfig = {
      ...originalConfig,
      project: {
        ...originalConfig.project,
        namespace: "https://w3id.org/example/vocab#",
        canonicalUri: "https://w3id.org/example/vocab"
      },
      sources: {
        ...originalConfig.sources,
        ontology: ontologyPath,
        ontologyFormat: "turtle"
      },
      persistentIri: {
        enabled: true,
        documentIri: "https://w3id.org/example/vocab",
        siteUrl: "https://example.github.io/example-ontology/",
        representations: [
          {
            mediaType: "application/ld+json",
            path: jsonldPath,
            destinationName: "vocabulary.jsonld"
          }
        ]
      }
    };
    fs.writeFileSync(configPath, JSON.stringify(testConfig, null, 2));
    execFileSync("node", ["scripts/build-site.mjs"], { cwd: ROOT, stdio: "pipe" });

    for (const relative of [
      "site/iri-resolver.html",
      "site/linked-data/ontology.ttl",
      "site/linked-data/vocabulary.jsonld",
      "site/persistent-iri/README.md",
      "site/persistent-iri/w3id-htaccess.txt",
      "site/persistent-iri/w3id/example/.htaccess"
    ]) {
      assert.equal(fs.existsSync(path.join(ROOT, relative)), true, `${relative} should exist`);
    }

    const resolverHtml = fs.readFileSync(path.join(ROOT, "site/iri-resolver.html"), "utf8");
    assert.match(resolverHtml, /const TERM_TARGETS = \{"ExampleTerm":"terms\/ExampleTerm\.html"\}/);
    assert.match(resolverHtml, /window\.location\.replace\(target\)/);
    assert.match(resolverHtml, /decodeURIComponent\(fragment\)/);

    const indexHtml = fs.readFileSync(path.join(ROOT, "site/index.html"), "utf8");
    assert.match(indexHtml, /rel="alternate" type="text\/turtle" href="https:\/\/example\.github\.io\/example-ontology\/linked-data\/ontology\.ttl"/);
    assert.match(indexHtml, /rel="alternate" type="application\/ld\+json" href="https:\/\/example\.github\.io\/example-ontology\/linked-data\/vocabulary\.jsonld"/);

    const htaccess = fs.readFileSync(path.join(ROOT, "site/persistent-iri/w3id-htaccess.txt"), "utf8");
    assert.match(htaccess, /RewriteCond %\{HTTP:Accept\} \(\^\|,\|\\s\)text\/turtle/);
    assert.match(htaccess, /RewriteCond %\{HTTP:Accept\} \(\^\|,\|\\s\)application\/ld\\\+json/);
    assert.match(htaccess, /https:\/\/example\.github\.io\/example-ontology\/linked-data\/ontology\.ttl/);
    assert.match(htaccess, /https:\/\/example\.github\.io\/example-ontology\/iri-resolver\.html/);
    assert.match(htaccess, /Header append Vary Accept/);

    const deploymentReadme = fs.readFileSync(path.join(ROOT, "site/persistent-iri/README.md"), "utf8");
    assert.match(deploymentReadme, /full ontology/);
    assert.match(deploymentReadme, /curl -L -H "Accept: text\/turtle"/);
  } finally {
    fs.writeFileSync(configPath, originalConfigText);
    fs.rmSync(tempDir, { recursive: true, force: true });
    execFileSync("node", ["scripts/build-site.mjs"], { cwd: ROOT, stdio: "pipe" });
  }
});

test("ocg CLI initializes and builds an external ontology repository", () => {
  const tempDir = fs.mkdtempSync(path.join(ROOT, ".ocg-cli-test-"));
  const sourcePath = path.join(ROOT, "source", "ontology", "example-capability.ttl");
  fs.copyFileSync(sourcePath, path.join(tempDir, "ontology.ttl"));

  try {
    const cliPath = path.join(ROOT, "bin", "ocg.mjs");
    execFileSync(process.execPath, [cliPath, "init", "--ontology", "ontology.ttl"], {
      cwd: tempDir,
      stdio: "pipe"
    });

    const config = JSON.parse(fs.readFileSync(path.join(tempDir, "ocg.config.json"), "utf8"));
    assert.equal(config.sources.ontology, "ontology.ttl");
    assert.equal(config.curation.autoFeaturedTerms, true);
    assert.equal(config.curation.featuredTermLimit, 6);
    assert.deepEqual(config.curation.viewerTabs, []);
    assert.equal(config.features.hierarchyOverview, false);
    assert.equal(config.persistentIri.enabled, false);
    assert.equal(config.persistentIri.documentIri, "");
    assert.equal(config.persistentIri.siteUrl, "");
    assert.deepEqual(config.persistentIri.representations, []);
    assert.equal(config.hierarchy.maxNodes, 36);
    assert.equal(config.project.namespace, "https://example.org/ecv#");
    assert.equal(config.site.home.overview.title, "Repository Workflow");
    assert.equal(config.site.home.viewer.title, "Artifact Viewer");
    assert.equal(config.site.home.artifacts.ontologyLabel, "OWL Ontology");
    assert.equal(config.site.toc.enabled, true);
    assert.equal(config.site.toc.title, "On this page");
    assert.equal(config.site.toc.collapseLabel, "Collapse page contents");
    assert.equal(config.site.toc.expandLabel, "Expand page contents");
    assert.equal(config.site.branding.headerImage, "");
    assert.equal(config.site.branding.favicon, "");
    assert.equal(fs.existsSync(path.join(tempDir, "ocg.config.schema.json")), true);
    assert.equal(fs.existsSync(path.join(tempDir, ".github", "workflows", "publish-pages.yml")), true);
    const projectPackage = JSON.parse(fs.readFileSync(path.join(tempDir, "package.json"), "utf8"));
    assert.equal(projectPackage.devDependencies["ontology-companion-generator"], `^${PACKAGE_VERSION}`);
    assert.equal(projectPackage.scripts["ocg:build"], "ocg build");
    assert.match(
      fs.readFileSync(path.join(tempDir, ".github", "workflows", "publish-pages.yml"), "utf8"),
      /npm run ocg:build/
    );

    execFileSync(process.execPath, [cliPath, "check"], { cwd: tempDir, stdio: "pipe" });
    execFileSync(process.execPath, [cliPath, "build"], { cwd: tempDir, stdio: "pipe" });
    const indexHtml = fs.readFileSync(path.join(tempDir, "site", "index.html"), "utf8");
    assert.match(indexHtml, /class="card featured-term-card"/);
    assert.match(indexHtml, /data-label="OWL Ontology"/);
    assert.doesNotMatch(indexHtml, /data-label="Config Schema"/);

    fs.writeFileSync(path.join(tempDir, "context.json"), "{\"example\":true}\n");
    fs.mkdirSync(path.join(tempDir, "branding"), { recursive: true });
    fs.writeFileSync(
      path.join(tempDir, "branding", "header.svg"),
      '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" fill="#13535a"/></svg>'
    );
    fs.writeFileSync(
      path.join(tempDir, "branding", "favicon.svg"),
      '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><circle cx="16" cy="16" r="14" fill="#1f6f78"/></svg>'
    );
    fs.writeFileSync(path.join(tempDir, "spec.html"), "<!doctype html><html><head><title>Spec</title></head><body><h1>Spec</h1></body></html>");
    config.site.home = {
      ...config.site.home,
      actions: {
        ...config.site.home.actions,
        reference: "Read the Reference",
        ontology: "Vocabulary Source"
      },
      metadata: {
        ...config.site.home.metadata,
        canonicalUri: "Vocabulary IRI",
        unspecified: "Not provided"
      },
      snapshot: {
        title: "Vocabulary at a Glance",
        body: "Counts derived from this vocabulary source."
      },
      overview: {
        title: "Using This Vocabulary",
        body: "Project-specific onboarding guidance."
      },
      featuredTerms: {
        ...config.site.home.featuredTerms,
        title: "Key Terms"
      },
      examples: {
        ...config.site.home.examples,
        title: "Example Data",
        defaultDescription: "Configured example data.",
        linkText: "View Example"
      },
      viewer: {
        title: "Source Viewer",
        body: "Select a published source file.",
        viewFileText: "View Source",
        loadingText: "Loading source..."
      },
      artifacts: {
        ...config.site.home.artifacts,
        ontologyLabel: "Vocabulary Source",
        ontologyDescription: "Published primary vocabulary file."
      }
    };
    config.project.title = "Example Capability Vocabulary for Distributed Research Infrastructure and Interoperable Services";
    config.project.shortName = "Example Capability Vocabulary";
    config.site.toc = {
      enabled: true,
      title: "Page map",
      collapseLabel: "Hide page map",
      expandLabel: "Show page map"
    };
    config.site.branding = {
      headerImage: "branding/header.svg",
      favicon: "branding/favicon.svg"
    };
    config.sources.spec = "spec.html";
    config.features.specPage = true;
    config.site.overviewCards = [
      {
        title: "Start Here",
        body: "Read the project guidance before using the vocabulary. This deliberately long card description confirms that editorial content can wrap naturally across multiple lines without being clipped by its container."
      }
    ];
    config.sources.artifacts = [
      {
        key: "context",
        label: "Context JSON",
        path: "context.json",
        description: "Additional metadata."
      }
    ];
    fs.writeFileSync(path.join(tempDir, "ocg.config.json"), JSON.stringify(config, null, 2));
    execFileSync(process.execPath, [cliPath, "build"], { cwd: tempDir, stdio: "pipe" });
    const artifactIndexHtml = fs.readFileSync(path.join(tempDir, "site", "index.html"), "utf8");
    assert.match(artifactIndexHtml, /Read the Reference/);
    assert.match(artifactIndexHtml, /Vocabulary Source/);
    assert.match(artifactIndexHtml, /<dt>Vocabulary IRI<\/dt>/);
    assert.match(artifactIndexHtml, /<h2>Vocabulary at a Glance<\/h2>/);
    assert.match(artifactIndexHtml, /Counts derived from this vocabulary source\./);
    assert.match(artifactIndexHtml, /<h2>Using This Vocabulary<\/h2>/);
    assert.match(artifactIndexHtml, /Project-specific onboarding guidance\./);
    assert.match(artifactIndexHtml, /Example Capability Vocabulary for Distributed Research Infrastructure and Interoperable Services/);
    assert.match(artifactIndexHtml, /This deliberately long card description confirms that editorial content can wrap naturally/);
    assert.match(artifactIndexHtml, /<h2>Key Terms<\/h2>/);
    assert.match(artifactIndexHtml, /<h2>Source Viewer<\/h2>/);
    assert.match(artifactIndexHtml, />View Source</);
    assert.match(artifactIndexHtml, /<aside class="page-toc" aria-label="Page map">/);
    assert.match(artifactIndexHtml, /aria-label="Hide page map"/);
    assert.match(artifactIndexHtml, /class="brand-mark brand-mark--image"><img src="assets\/branding\/header-image\.svg"/);
    assert.match(artifactIndexHtml, /rel="icon" type="image\/svg\+xml" href="favicon\.svg"/);
    assert.doesNotMatch(artifactIndexHtml, /<h2>Repository Workflow<\/h2>/);
    assert.doesNotMatch(artifactIndexHtml, /These cards come directly from ocg\.config\.json/);
    assert.match(artifactIndexHtml, /data-label="Vocabulary Source"/);
    assert.match(artifactIndexHtml, /data-file="assets\/context\.json"/);
    assert.match(artifactIndexHtml, /data-label="Context JSON"/);
    assert.equal(fs.existsSync(path.join(tempDir, "site", "assets", "context.json")), true);
    assert.equal(fs.existsSync(path.join(tempDir, "site", "assets", "branding", "header-image.svg")), true);
    assert.equal(fs.existsSync(path.join(tempDir, "site", "favicon.svg")), true);
    const specHtml = fs.readFileSync(path.join(tempDir, "site", "spec", "index.html"), "utf8");
    assert.match(specHtml, /class="brand-mark brand-mark--image"><img src="\.\.\/assets\/branding\/header-image\.svg"/);
    assert.match(specHtml, /rel="icon" type="image\/svg\+xml" href="\.\.\/favicon\.svg"/);
    const graphData = JSON.parse(
      fs.readFileSync(path.join(tempDir, "site", "assets", "ontology_graph_data.json"), "utf8")
    );
    assert.ok(graphData.nodes.length > 0);
    assert.equal(fs.existsSync(path.join(tempDir, "site", "assets", "vendor", "sigma.min.js")), true);
  } finally {
    fs.rmSync(tempDir, { recursive: true, force: true });
  }
});

test("term pages never overwrite the generated terms listing", () => {
  const tempDir = fs.mkdtempSync(path.join(ROOT, ".ocg-term-conflict-test-"));
  try {
    const cliPath = path.join(ROOT, "bin", "ocg.mjs");
    fs.copyFileSync(path.join(ROOT, "tests", "fixtures", "conflicting-terms.ttl"), path.join(tempDir, "ontology.ttl"));
    execFileSync(process.execPath, [cliPath, "init", "--ontology", "ontology.ttl"], { cwd: tempDir, stdio: "pipe" });
    execFileSync(process.execPath, [cliPath, "build"], { cwd: tempDir, stdio: "pipe" });

    const termsDir = path.join(tempDir, "site", "terms");
    const listingHtml = fs.readFileSync(path.join(termsDir, "index.html"), "utf8");
    assert.match(listingHtml, /<h1>Term Pages<\/h1>/, "terms/index.html should still be the generated listing");

    const graphData = JSON.parse(fs.readFileSync(path.join(tempDir, "site", "assets", "ontology_graph_data.json"), "utf8"));
    const declared = graphData.nodes.filter((node) => !node.isExternal);
    const pageNameFor = (qname) => declared.find((node) => node.qname === qname)?.pageName;
    assert.ok(declared.every((node) => node.pageName), "every declared term should receive a page name");
    assert.equal(
      declared.some((node) => node.pageName.toLowerCase() === "index"),
      false,
      "no term page may claim the reserved 'index' name"
    );

    // cft:index would have overwritten the listing; cft:Index would have collided
    // with it on a case-insensitive file system.
    const indexTermPage = pageNameFor("cft:index");
    assert.match(listingHtml, new RegExp(`href="${escapeRegExp(indexTermPage)}\\.html"`));
    assert.match(fs.readFileSync(path.join(termsDir, `${indexTermPage}.html`), "utf8"), /cft:index/);
    assert.notEqual(pageNameFor("cft:Index").toLowerCase(), indexTermPage.toLowerCase());
    assert.equal(pageNameFor("cft:Record"), "Record");

    const generated = fs.readdirSync(termsDir).filter((entry) => entry.endsWith(".html"));
    const lowercased = generated.map((entry) => entry.toLowerCase());
    assert.equal(new Set(lowercased).size, lowercased.length, "generated term pages must be unique case-insensitively");

    const indexHtml = fs.readFileSync(path.join(tempDir, "site", "index.html"), "utf8");
    assert.match(indexHtml, /<dt>Preferred Prefix<\/dt>\s*<dd><code>cft<\/code><\/dd>/);
    assert.equal(graphData.ontology.preferredNamespacePrefix, "cft");
    assert.equal(graphData.ontology.preferredNamespaceUri, "https://example.org/cft#");
  } finally {
    fs.rmSync(tempDir, { recursive: true, force: true });
  }
});

test("the optional OOPS! pitfall scanner renders the returned report", async () => {
  const oopsResponse = `<rdf:RDF
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:oops="http://oops.linkeddata.es/def#" >
  <rdf:Description rdf:about="http://oops.linkeddata.es/data/pitfall-1">
    <oops:hasCode rdf:datatype="http://www.w3.org/2001/XMLSchema#string">P04</oops:hasCode>
    <oops:hasName rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Creating unconnected ontology elements</oops:hasName>
    <oops:hasDescription rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Ontology elements are created isolated.</oops:hasDescription>
    <oops:hasImportanceLevel rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Minor</oops:hasImportanceLevel>
    <oops:hasNumberAffectedElements rdf:datatype="http://www.w3.org/2001/XMLSchema#integer">1</oops:hasNumberAffectedElements>
    <oops:hasAffectedElement rdf:datatype="http://www.w3.org/2001/XMLSchema#anyURI">https://example.org/ecv#Capability</oops:hasAffectedElement>
    <rdf:type rdf:resource="http://oops.linkeddata.es/def#pitfall"/>
  </rdf:Description>
  <rdf:Description rdf:about="http://oops.linkeddata.es/data/pitfall-2">
    <oops:hasCode rdf:datatype="http://www.w3.org/2001/XMLSchema#string">P10</oops:hasCode>
    <oops:hasName rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Missing disjointness</oops:hasName>
    <oops:hasDescription rdf:datatype="http://www.w3.org/2001/XMLSchema#string">The ontology lacks disjoint axioms.</oops:hasDescription>
    <oops:hasImportanceLevel rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Important</oops:hasImportanceLevel>
    <oops:hasNumberAffectedElements rdf:datatype="http://www.w3.org/2001/XMLSchema#integer">0</oops:hasNumberAffectedElements>
    <rdf:type rdf:resource="http://oops.linkeddata.es/def#pitfall"/>
  </rdf:Description>
</rdf:RDF>`;

  const requests = [];
  const server = createServer((request, response) => {
    const chunks = [];
    request.on("data", (chunk) => chunks.push(chunk));
    request.on("end", () => {
      requests.push({ method: request.method, body: Buffer.concat(chunks).toString("utf8") });
      response.writeHead(200, { "Content-Type": "application/rdf+xml" });
      response.end(oopsResponse);
    });
  });
  await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
  const serviceUrl = `http://127.0.0.1:${server.address().port}/rest`;

  const tempDir = fs.mkdtempSync(path.join(ROOT, ".ocg-pitfall-test-"));
  try {
    const cliPath = path.join(ROOT, "bin", "ocg.mjs");
    fs.copyFileSync(path.join(ROOT, "source", "ontology", "example-capability.ttl"), path.join(tempDir, "ontology.ttl"));
    execFileSync(process.execPath, [cliPath, "init", "--ontology", "ontology.ttl"], { cwd: tempDir, stdio: "pipe" });

    const configPath = path.join(tempDir, "ocg.config.json");
    const config = JSON.parse(fs.readFileSync(configPath, "utf8"));
    assert.equal(config.pitfallScanner.enabled, false, "the scanner must stay opt-in for new projects");
    config.pitfallScanner = { ...config.pitfallScanner, enabled: true, serviceUrl, timeoutMs: 15000, failOnError: true, cache: false };
    fs.writeFileSync(configPath, JSON.stringify(config, null, 2));
    await execFileAsync(process.execPath, [cliPath, "build"], { cwd: tempDir });

    assert.equal(requests.length, 1);
    assert.equal(requests[0].method, "POST");
    // Turtle input has to reach OOPS! as RDF/XML.
    assert.match(requests[0].body, /<OOPSRequest>/);
    assert.match(requests[0].body, /<OutputFormat>RDF\/XML<\/OutputFormat>/);
    assert.match(requests[0].body, /<!\[CDATA\[<\?xml version="1\.0" encoding="UTF-8"\?>\s*<rdf:RDF/);
    assert.match(requests[0].body, /rdf:about="https:\/\/example\.org\/ecv#Capability"/);

    const pitfallHtml = fs.readFileSync(path.join(tempDir, "site", "ontology-pitfalls.html"), "utf8");
    assert.match(pitfallHtml, /<h2>Ontology Pitfalls<\/h2>/);
    assert.match(pitfallHtml, />P04</);
    assert.match(pitfallHtml, />P10</);
    assert.match(pitfallHtml, /Creating unconnected ontology elements/);
    assert.match(pitfallHtml, /href="terms\/Capability\.html"/);
    assert.match(pitfallHtml, /Reported for the ontology as a whole\./);
    assert.match(pitfallHtml, /href="ontology-pitfalls\.html">Pitfalls</);
    // Important pitfalls sort ahead of minor ones.
    assert.ok(pitfallHtml.indexOf(">P10<") < pitfallHtml.indexOf(">P04<"));

    const report = JSON.parse(fs.readFileSync(path.join(tempDir, "site", "assets", "ontology_pitfalls.json"), "utf8"));
    assert.equal(report.available, true);
    assert.equal(report.summary.total, 2);
    assert.deepEqual(report.summary.byImportance, { Important: 1, Minor: 1 });
    assert.deepEqual(report.pitfalls.map((pitfall) => pitfall.code), ["P10", "P04"]);

    const homeHtml = fs.readFileSync(path.join(tempDir, "site", "index.html"), "utf8");
    assert.match(homeHtml, /href="ontology-pitfalls\.html">Pitfalls</);
  } finally {
    fs.rmSync(tempDir, { recursive: true, force: true });
    await new Promise((resolve) => server.close(resolve));
  }
});

test("an OOPS! error document is surfaced instead of an empty pitfall report", async () => {
  // Shape captured from the live service when it cannot read the submitted ontology.
  // Note the older oeg-upm.net vocabulary namespace, which OCG must still recognize.
  const errorResponse = `<rdf:RDF
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:oops="http://www.oeg-upm.net/oops#" >
  <rdf:Description rdf:about="http://www.oeg-upm.net/oops/unexpected_error">
    <oops:hasTitle rdf:datatype="http://www.w3.org/2001/XMLSchema#string">OOPS! something went wrong.</oops:hasTitle>
    <oops:hasMessage rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Make sure that your ontology RDF or OWL code is correct.</oops:hasMessage>
    <rdf:type rdf:resource="http://www.oeg-upm.net/oops#response"/>
  </rdf:Description>
</rdf:RDF>`;

  const server = createServer((request, response) => {
    request.resume();
    request.on("end", () => {
      response.writeHead(200, { "Content-Type": "application/rdf+xml" });
      response.end(errorResponse);
    });
  });
  await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
  const serviceUrl = `http://127.0.0.1:${server.address().port}/rest`;

  const tempDir = fs.mkdtempSync(path.join(ROOT, ".ocg-pitfall-error-test-"));
  try {
    const cliPath = path.join(ROOT, "bin", "ocg.mjs");
    fs.copyFileSync(path.join(ROOT, "source", "ontology", "example-capability.ttl"), path.join(tempDir, "ontology.ttl"));
    execFileSync(process.execPath, [cliPath, "init", "--ontology", "ontology.ttl"], { cwd: tempDir, stdio: "pipe" });

    const configPath = path.join(tempDir, "ocg.config.json");
    const config = JSON.parse(fs.readFileSync(configPath, "utf8"));
    config.pitfallScanner = { ...config.pitfallScanner, enabled: true, serviceUrl, timeoutMs: 15000, failOnError: false, cache: false };
    fs.writeFileSync(configPath, JSON.stringify(config, null, 2));
    await execFileAsync(process.execPath, [cliPath, "build"], { cwd: tempDir });

    const report = JSON.parse(fs.readFileSync(path.join(tempDir, "site", "assets", "ontology_pitfalls.json"), "utf8"));
    assert.equal(report.available, false);
    assert.equal(report.pitfalls.length, 0);
    assert.match(report.error, /OOPS! rejected the ontology/);
    assert.match(report.error, /something went wrong/);
    const pitfallHtml = fs.readFileSync(path.join(tempDir, "site", "ontology-pitfalls.html"), "utf8");
    assert.match(pitfallHtml, /Report unavailable\./);
    assert.doesNotMatch(pitfallHtml, /<h2>Detected Pitfalls<\/h2>/);
  } finally {
    fs.rmSync(tempDir, { recursive: true, force: true });
    await new Promise((resolve) => server.close(resolve));
  }
});

test("a failing pitfall scan degrades instead of breaking the build", async () => {
  const server = createServer((request, response) => {
    // The request body has to be drained before responding, otherwise the client
    // is still uploading when the response is written and the exchange stalls.
    request.resume();
    request.on("end", () => {
      response.writeHead(503, { "Content-Type": "text/plain" });
      response.end("unavailable");
    });
  });
  await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
  const serviceUrl = `http://127.0.0.1:${server.address().port}/rest`;

  const tempDir = fs.mkdtempSync(path.join(ROOT, ".ocg-pitfall-failure-test-"));
  try {
    const cliPath = path.join(ROOT, "bin", "ocg.mjs");
    fs.copyFileSync(path.join(ROOT, "source", "ontology", "example-capability.ttl"), path.join(tempDir, "ontology.ttl"));
    execFileSync(process.execPath, [cliPath, "init", "--ontology", "ontology.ttl"], { cwd: tempDir, stdio: "pipe" });

    const configPath = path.join(tempDir, "ocg.config.json");
    const config = JSON.parse(fs.readFileSync(configPath, "utf8"));
    config.pitfallScanner = { ...config.pitfallScanner, enabled: true, serviceUrl, timeoutMs: 15000, failOnError: false, cache: false };
    fs.writeFileSync(configPath, JSON.stringify(config, null, 2));
    await execFileAsync(process.execPath, [cliPath, "build"], { cwd: tempDir });

    const pitfallHtml = fs.readFileSync(path.join(tempDir, "site", "ontology-pitfalls.html"), "utf8");
    assert.match(pitfallHtml, /Report unavailable\./);
    assert.match(pitfallHtml, /HTTP 503/);
    const report = JSON.parse(fs.readFileSync(path.join(tempDir, "site", "assets", "ontology_pitfalls.json"), "utf8"));
    assert.equal(report.available, false);
    assert.match(report.error, /HTTP 503/);
  } finally {
    fs.rmSync(tempDir, { recursive: true, force: true });
    await new Promise((resolve) => server.close(resolve));
  }
});

test("embedded JSON-LD is a faithful subset of the parsed ontology", async () => {
  const { rdfParser } = await import("rdf-parse");
  const { Readable } = await import("node:stream");

  const parse = (content, contentType, baseIRI) =>
    new Promise((resolve, reject) => {
      const quads = [];
      rdfParser
        .parse(Readable.from([content]), { contentType, baseIRI })
        .on("data", (quad) => quads.push(quad))
        .on("error", reject)
        .on("end", () => resolve(quads));
    });
  const asTriple = (quad) =>
    [
      quad.subject.value,
      quad.predicate.value,
      quad.object.termType === "Literal"
        ? `"${quad.object.value}"@${quad.object.language}^^${quad.object.datatype?.value ?? ""}`
        : quad.object.value
    ].join(" | ");

  const sourceQuads = await parse(
    fs.readFileSync(path.join(ROOT, "source", "ontology", "example-capability.ttl"), "utf8"),
    "text/turtle",
    "https://example.org/ecv"
  );
  const sourceTriples = new Set(sourceQuads.map(asTriple));
  const ONTOLOGY_IRI = "https://example.org/ecv";
  const IS_DEFINED_BY = "http://www.w3.org/2000/01/rdf-schema#isDefinedBy";

  // rdf-parse handles text/html, so the generated pages can be read back exactly
  // the way a crawler would read them.
  const triplesFromPage = async (relativePath) =>
    parse(fs.readFileSync(path.join(ROOT, relativePath), "utf8"), "text/html", "https://example.org/page");

  const termQuads = await triplesFromPage("site/terms/Capability.html");
  assert.ok(termQuads.length > 0, "the term page should expose parseable RDF");

  // Every page in the site must only assert triples the ontology already contains,
  // apart from the rdfs:isDefinedBy statement OCG adds itself.
  for (const relativePath of [
    "site/index.html",
    "site/ontology-reference.html",
    "site/terms/Capability.html",
    "site/terms/OnlineCapability.html",
    "site/terms/PublisherAudience.html",
    "site/terms/hasRequirement.html"
  ]) {
    const quads = await triplesFromPage(relativePath);
    assert.ok(quads.length > 0, `${relativePath} should embed JSON-LD`);
    for (const quad of quads) {
      if (quad.predicate.value === IS_DEFINED_BY) {
        assert.equal(quad.object.value, ONTOLOGY_IRI, `${relativePath} should link terms to the ontology IRI`);
        continue;
      }
      assert.ok(
        sourceTriples.has(asTriple(quad)),
        `${relativePath} asserts a triple that is not in the source ontology: ${asTriple(quad)}`
      );
    }
  }

  const termTriples = new Set(termQuads.map(asTriple));
  assert.ok(termTriples.has("https://example.org/ecv#Capability | http://www.w3.org/1999/02/22-rdf-syntax-ns#type | http://www.w3.org/2002/07/owl#Class"));
  assert.ok(termTriples.has('https://example.org/ecv#Capability | http://www.w3.org/2000/01/rdf-schema#label | "Capability"@en^^http://www.w3.org/1999/02/22-rdf-syntax-ns#langString'));

  // The normalized node model collapses skos:prefLabel into `label`; republishing
  // it as rdfs:label would invent a triple the ontology never had.
  const conceptTriples = new Set((await triplesFromPage("site/terms/PublisherAudience.html")).map(asTriple));
  assert.ok(
    conceptTriples.has('https://example.org/ecv#PublisherAudience | http://www.w3.org/2004/02/skos/core#prefLabel | "Publisher Audience"@en^^http://www.w3.org/1999/02/22-rdf-syntax-ns#langString'),
    "a skos:prefLabel must be republished as skos:prefLabel"
  );

  // Relationships OCG models as graph edges come back as real predicates.
  const propertyTriples = new Set((await triplesFromPage("site/terms/hasRequirement.html")).map(asTriple));
  for (const expected of [
    "https://example.org/ecv#hasRequirement | http://www.w3.org/2000/01/rdf-schema#domain | https://example.org/ecv#Capability",
    "https://example.org/ecv#hasRequirement | http://www.w3.org/2000/01/rdf-schema#range | https://example.org/ecv#Requirement"
  ]) {
    assert.ok(propertyTriples.has(expected), `hasRequirement should embed ${expected}`);
  }
  const subClassTriples = new Set((await triplesFromPage("site/terms/OnlineCapability.html")).map(asTriple));
  assert.ok(subClassTriples.has("https://example.org/ecv#OnlineCapability | http://www.w3.org/2000/01/rdf-schema#subClassOf | https://example.org/ecv#Capability"));

  // The home page carries the ontology header; the reference page the whole vocabulary.
  const homeTriples = new Set((await triplesFromPage("site/index.html")).map(asTriple));
  assert.ok(homeTriples.has(`${ONTOLOGY_IRI} | http://www.w3.org/1999/02/22-rdf-syntax-ns#type | http://www.w3.org/2002/07/owl#Ontology`));
  assert.ok(homeTriples.has(`${ONTOLOGY_IRI} | http://purl.org/vocab/vann/preferredNamespacePrefix | "ecv"@^^http://www.w3.org/2001/XMLSchema#string`));

  const referenceQuads = await triplesFromPage("site/ontology-reference.html");
  const referenceSubjects = new Set(referenceQuads.map((quad) => quad.subject.value));
  const graphData = JSON.parse(fs.readFileSync(path.join(ROOT, "site/assets/ontology_graph_data.json"), "utf8"));
  for (const node of graphData.nodes.filter((entry) => !entry.isExternal)) {
    assert.ok(referenceSubjects.has(node.uri), `the reference page graph should describe ${node.qname}`);
  }
  assert.ok(referenceSubjects.has(ONTOLOGY_IRI));
});

test("features.embeddedJsonLd can be switched off", () => {
  const tempDir = fs.mkdtempSync(path.join(ROOT, ".ocg-jsonld-test-"));
  try {
    const cliPath = path.join(ROOT, "bin", "ocg.mjs");
    fs.copyFileSync(path.join(ROOT, "source", "ontology", "example-capability.ttl"), path.join(tempDir, "ontology.ttl"));
    execFileSync(process.execPath, [cliPath, "init", "--ontology", "ontology.ttl"], { cwd: tempDir, stdio: "pipe" });

    const configPath = path.join(tempDir, "ocg.config.json");
    const config = JSON.parse(fs.readFileSync(configPath, "utf8"));
    assert.equal(config.features.embeddedJsonLd, true, "new projects should embed JSON-LD by default");
    config.features.embeddedJsonLd = false;
    fs.writeFileSync(configPath, JSON.stringify(config, null, 2));
    execFileSync(process.execPath, [cliPath, "build"], { cwd: tempDir, stdio: "pipe" });

    for (const relative of ["site/index.html", "site/ontology-reference.html", "site/terms/Capability.html"]) {
      assert.doesNotMatch(
        fs.readFileSync(path.join(tempDir, relative), "utf8"),
        /application\/ld\+json/,
        `${relative} should not embed JSON-LD when the feature is off`
      );
    }
  } finally {
    fs.rmSync(tempDir, { recursive: true, force: true });
  }
});
